### ISSUE TITLE
Lazy seems to error out when quitting nvim

### ISSUE THREAD

**Issue by i3d** [sschleemilch/slimline.nvim#1]
Here is the stacktrace I observed

```
Error in decoration provider virt-column.win:
Error executing lua: ...hare/nvim/lazy/virt-column.nvim/lua/virt-column/init.lua:33: Vim:E315: ml_get: Invalid lnum: 1
stack traceback:
        [C]: in function 'nvim_win_call'
        ...hare/nvim/lazy/virt-column.nvim/lua/virt-column/init.lua:33: in function <...hare/nvim/lazy/virt-column.nvim/lua/virt-column/init.lua:19>
        [C]: in function 'redrawstatus'
        ...ocal/share/nvim/lazy/slimline.nvim/lua/slimline/init.lua:49: in function 'refresh'
        ...re/nvim/lazy/slimline.nvim/lua/slimline/autocommands.lua:14: in function <...re/nvim/lazy/slimline.nvim/lua/slimline/autocommands.lua:13>
        [C]: in function 'nvim_exec_autocmds'
        ...e/.local/share/nvim/runtime/lua/vim/diagnostic.lua:2055: in function 'reset'
        ...e/.local/share/nvim/runtime/lua/vim/lsp.lua:526: in function 'buf_detach_client'
        ...e/.local/share/nvim/runtime/lua/vim/lsp.lua:605: in function <...e/.local/share/nvim/runtime/lua/vim/lsp.lua:602>
```

config is like this

```
return {
    -- Calls `require('slimline').setup({})`
    "sschleemilch/slimline.nvim",
    opts = {
        bold = true,
        verbose_mode = true,
        style = "fg",
        spaces = {
            components = "─",
            left = "",
            right  = ""
        },
        sep = {
            hide = {
                first = true,
                last = true,
            },
            left = "<U+E0BA>",
            right = "<U+E0BC>"
        }
    },
}
```

**Comment by i3d** [comment]
one other thing I noticed is that the dir information seems only have `.` as indicating of the current dir? It would be nice if it could provide the current dir full name [or better like the screenshot you had `lua/slimline`  -- a parent and current dir.
![Screenshot 2024-08-25 at 10 18 43 PM](https://github.com/user-attachments/assets/b7b47613-38a1-46c0-91b2-27a52d704a8c)

**Comment by sschleemilch** [comment]
> Here is the stacktrace I observed

Interesting, I will see what I can do. Does it happen on every quit of nvim? In what log can I find the stacktrace? Mine `.local/state/log` does not show it.

> seems only have . as indicating of the current dir?

Yeah.. but might be indeed a good idea to show a bit of context when being in cwd.
Personally I am usually only interested in the path to the current buffer in my project but I can see that it might be good to have more context.

**Comment by i3d** [comment]
it emits to :messages, so dumped the messages out. yeah, it does it constantly on every exit. I have not yet tried reduce the my config, I thought my config [for this plugin] is relatively straightforward, or perhaps you are talking about reducing the entire config into some minimum, I also didn't try that but let me see what I can do...

**Comment by sschleemilch** [comment]
I think I might have fixed it by removing the `DiagnosticChanged` autocommand which seems to be the reason here in the stacktrace. Can you update and see whether this fixes your issue?

**Comment by sschleemilch** [comment]
> I have not yet tried reduce the my config

All good, I meant the overall nvim plugin config to for instance only include a colorscheme and slimline but I am quite sure I did not quite understand the `DiagnosticChanged` Autocommand here :no_good:

**Comment by i3d** [comment]
ah sorry, I am slow on my side, yeah, definitely will give a try.

**Comment by i3d** [comment]
indeed, it is fixed. Thank you so much! The 'fg' feature is attractive since it could blend into the rest of theme really well.
