### ISSUE TITLE
Opening a floating window changes colors of separators

### ISSUE THREAD

**Issue by nmiguel** [sschleemilch/slimline.nvim#16]
When a floating window is open (lazygit, telescope, Lazy), the colors of the separators change in a way that makes them stand out from the rest of the background (see example):
Normal:
![image](https://github.com/user-attachments/assets/8640ec58-f89d-40cc-8479-a7f601d9042a)

With floating window:
![image](https://github.com/user-attachments/assets/e5a1db5e-c5cd-4264-b828-397cde5808f6)

This happens with the default configuration (called `require("slimline").setup({})`)

**Comment by sschleemilch** [comment]
Thanks for reporting this issue.
Weird, it does not happen for me.
Does it change when you are using a different colorscheme? Is that a complete transparent scheme?
Any chance I can reproduce that somehow? I am not sure what is happening. Slimline at least does not listen to floating windows and changes highlights in any way dynamically

**Comment by nmiguel** [comment]
The fact that you can't replicate lead me to investigate further (I had tried different themes and replicated with them all). Turns out the culprit is a plugin for dimming out of focus windows.
