### ISSUE TITLE
This plugin only seems to work with nvim's nightly build

### ISSUE THREAD

**Issue by Hyuga-Tsukui** [sschleemilch/slimline.nvim#22]
This plugin only seems to work with nvim's nightly build

Wouldn't it be more helpful to have it listed in the repository description?

**Comment by sschleemilch** [comment]
Thanks for the Feedback. As far as I know 0.10.1 is the current stable version and also what I am using, so not a nightly...
But sure, I can add that info in the description.

**Comment by Hyuga-Tsukui** [comment]
I am sorry! It was a premature error on my part.
The problem was that my local NVIM version was too old.

If it works with the stable version, I didn't think it was necessary to mention it. Thanks for the good plugin!
