### ISSUE TITLE
bug: slimline freezes nvim when closing buffers

### ISSUE THREAD

**Issue by XavierChanth** [sschleemilch/slimline.nvim#27]
The following keymap causes nvim to freeze on occasion - completely unresponsive:

```
vim.keymap.set("n", "<leader>bo", "<cmd>%bd|e#|bd#<cr>", { desc = "Delete Other Buffers" })
```

Sadly I'm not able to reproduce consistently, but maybe you have an idea why?

Slimline itself contains the render function, instead of show its UI:

```
require('slimline').render()
```

Sorry I can't give more info 😞

**Comment by sschleemilch** [comment]
Hey,
thanks for reporting an issue.

I tried reproducing that by using your keymap and with several open buffers. It works fine for me.
Does it happen every time?

Does it also happen when disabling slimline?

**Comment by XavierChanth** [comment]
> Hey, thanks for reporting an issue.
> 
> I tried reproducing that by using your keymap and with several open buffers. It works fine for me. Does it happen every time?
> 
> Does it also happen when disabling slimline?

Sorry, I missed your comment in my notifications! It doesn't happen consistently, but it has been happening more frequently... I am able `:q` though now.

I think it may be a race condition with rendering, it seems to happen more when I'm moving fast and things that should show up in slimline change due to a keymap or plugin, like filetype and diagnostics.

When I get more conclusive information I will add another comment.

**Comment by XavierChanth** [comment]
Hey @sschleemilch, I'm going to close this. I have been using slimline for a few months and I've not had it happen again.

**Comment by sschleemilch** [comment]
Good to know. Thanks!
