### ISSUE TITLE
Support for Macro Recording Status in Status Line ?

### ISSUE THREAD

**Issue by Hyuga-Tsukui** [sschleemilch/slimline.nvim#30]
Hello,

Thank you for the fantastic plugin! I’m using slimline.nvim to enrich my status line, and it works beautifully. One enhancement I’d like to suggest is displaying the macro recording status (e.g., “recording `@a`”) directly within the status line. Since macro recording is a common status that many users might find helpful, I feel it could enhance the plugin's usability.

While I was able to achieve this using a custom component as follows:

```lua
require("slimline").setup({
  components = {
    left = {
      "mode",
      function()
        local h = require("slimline.highlights")
        local recording = vim.fn.reg_recording()
        if recording ~= "" then
          return h.hl_component({ primary = "recording @" .. recording }, h.hls.component, {
            hide = { first = true, last = true },
          })
        end
        return ""
      end,
      "path",
      "git",
    },
  },
})

```
![image](https://github.com/user-attachments/assets/7b5fa716-f16e-45dc-a910-f329f2d774f6)

It would still be great if this could be included as a built-in feature for easier integration and consistency.

I’m curious if there are any plans to officially support the macro recording status in a future release. If not, no worries – the current flexibility with custom components covers my needs.

Thank you again for all your hard work!

**Comment by sschleemilch** [comment]
Hi,

thanks a lot for that request.
I think it totally makes sense to have that. In fact, I am also struggling sometimes with hitting record accidentally and therefore it would make total sense to include that.

Thanks for the initial custom implementation. Looks pretty simple. I will have a look and implement it ❤️

**Comment by Hyuga-Tsukui** [comment]
Thank you so much for your positive response! I’m really glad to hear that this feature would be useful for you as well.

I haven’t implemented it yet, but I’d love to give it a try if that’s okay. I think it would be a great learning experience, and I’d be happy to submit a pull request if I can get it working well. Would you be open to reviewing it if I give it a shot?

**Comment by sschleemilch** [comment]
> Would you be open to reviewing it if I give it a shot?

Of course. Have fun :-)

**Comment by Hyuga-Tsukui** [comment]
Hi,
I’ve gone ahead and implemented the feature, and I’ve just submitted a pull request for it. The PR includes a recording component that displays the macro recording status (e.g., recording `@a`).
Please take a look when you have time – I’d appreciate any feedback or suggestions for improvement! #31
